### ISSUE TITLE
Documentation says input is factor, but can be character

### ISSUE THREAD

**Issue by robinsones** [tidyverse/forcats#102]
Documentation for functions (e.g. `fct_reorder`) say that the first input is a factor. But because of `check_factor`, they can actually be a character instead and will be converted to a factor. I think it would be clearer to surface this, so people aren't needlessly doing `as.factor` before using forcats functions. If you agree, I can make a pull request to update the documentation.

**Comment by hadley** [comment]
A PR would be great!
