### ISSUE TITLE
FR: Some kind of "fct_if_else()" or "fct_case_when()" implementation

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/forcats#105]
It often happens when I need to switch the factor levels of some cases based on a predicate. For instance, say I have this data set:

```
mydata <- data_frame(f1 = factor(c("A", "F", "C", "G")), f2 = factor(c("D", 
  "B", "D", "M")), cond = c(1L, 1L, 0L, 0L))
mydata
#> # A tibble: 4 x 3
#>   f1    f2     cond
#>   <fct> <fct> <int>
#> 1 A     D         1
#> 2 F     B         1
#> 3 C     D         0
#> 4 G     M         0
```

And for whatever reason, I need to have any cases where `cond == 0` have the factor levels set from whatever they are to "Z". It's very easy to get caught into doing this:

```
mutate_at(mydata, vars(starts_with("f")), funs(ifelse(cond == 0, "Z", .)))
#> # A tibble: 4 x 3
#>   f1    f2     cond
#>   <chr> <chr> <int>
#> 1 1     2         1
#> 2 3     1         1
#> 3 Z     Z         0
#> 4 Z     Z         0
```
I understand that this is an example why it's better to use `dplyr::if_else()` instead of `base::ifelse()`, but the point is it's easy to mess up the factor variables in this situation. 

Currently, as far I can see, I need to do this to not ruin my data:

```
mutate_at(mydata, vars(starts_with("f")), funs(if_else(cond == 0, "Z", as.character(.)) %>% 
  factor()))
#> # A tibble: 4 x 3
#>   f1    f2     cond
#>   <fct> <fct> <int>
#> 1 A     D         1
#> 2 F     B         1
#> 3 Z     Z         0
#> 4 Z     Z         0
```

But this is not ideal because I may have already worked on setting the factor levels in some way using `fct_recode()`, `fct_relevel()`, or even delete some levels with 0 cases that I actually wanted preserved, and this step has ruined all that earlier work.

**Comment by hadley** [comment]
This seems like a slightly odd thing to do with a factor - because you're adding a new level that doesn't already exist. I think the easiest solution would be to turn into a character vector, manipulate, and then turn back into a factor.

Alternatively, you could make your own wrapper function:

``` r
library(tidyverse)

df <- tibble(
  f1 = factor(c("A", "F", "C", "G")), 
  f2 = factor(c("D", "B", "D", "M")), 
  cond = c(1L, 1L, 0L, 0L)
)

change_level <- function(f, cond, level) {
  f <- fct_expand(f, level)
  f[cond] <- level
  f
}

df %>% 
  mutate_at(
    vars(f1, f2),
    funs(change_level(., cond == 0, "Z"))
  )
#> # A tibble: 4 x 3
#>   f1    f2     cond
#>   <fct> <fct> <int>
#> 1 A     D         1
#> 2 F     B         1
#> 3 Z     Z         0
#> 4 Z     Z         0
```

Created on 2018-02-11 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).
