### ISSUE TITLE
Feature request: reorder factor levels using a user-supplied sorting function

### ISSUE THREAD

**Issue by russHyde** [tidyverse/forcats#117]
Hi,
I was wondering whether you might consider adding a function to `forcats` that sets up factor levels according to a numerically-aware string-sorting method like gtools::mixedsort. 
There's a number of use cases: eg, when you end up with genomes ordered like "chr1", "chr10", "chr11" ... "chr2" rather than "chr1", "chr2", ..., in a plot if you don't hack your factors correctly

eg, 
```
fct_alphameric/fct_alnum/fct_mixedsort <- function(x, ...) {
    factor(x, levels = gtools::mixedsort(unique(x), ...))
    }
```

**Comment by huftis** [comment]
I think a better, more general solution would be a function to sort the levels according to a user-defined sort function. Here’s an implementation suggestion:

``` r
library(forcats)
fct_sort = function(.f, .fun = sort) {
  .f = forcats:::check_factor(.f) # Not needed in dev version
  fct_relevel(.f, .fun(levels(.f)))
}

x = c("chr1", "chr11", "chr10", "chr2")
fct_sort(x)
#> [1] chr1  chr11 chr10 chr2 
#> Levels: chr1 chr10 chr11 chr2
fct_sort(x, gtools::mixedsort)
#> [1] chr1  chr11 chr10 chr2 
#> Levels: chr1 chr2 chr10 chr11
```

And perhaps support for a custom *order* function (e.g. `gtools::mixedorder`) in addition to a custom sort function would also be useful?

**Comment by billdenney** [comment]
FYI, `naturalsort::naturalfactor` does what I think is being requested (working only for natural numbers).

**Comment by hadley** [comment]
I agree with @huftis that a more general `fct_sort()` is the better interface here

**Comment by russHyde** [comment]
Cool. Would you like me to work on a PR? (I'd forgotten I opened this issue)

**Comment by hadley** [comment]
Sure!
