### ISSUE TITLE
fct_lump yields different number of factor levels for the same `n` when `w` is specified

### ISSUE THREAD

**Issue by s-fleck** [tidyverse/forcats#118]
I get a weird behaviour in forcats 0.3.0.9000 where `fct_lump()` produces different numbers of factor levels for the same `n` when executed in sequence:

```
x <- data.frame(
  fct = factor(c("E", "T", "U", "K", "V", "Z")),
  wt = c(4, 2, 8, 4, 5, 4),
  stringsAsFactors = FALSE
)

x$fct2 <- forcats::fct_lump(x$fct, w = x$wt, n = 2)
x$fct3 <- forcats::fct_lump(x$fct2, w = x$wt, n = 2)

print(x)

#   fct wt  fct2  fct3
# 1   E  4 Other Other
# 2   T  2 Other Other
# 3   U  8     U     U
# 4   K  4 Other Other
# 5   V  5     V Other
# 6   Z  4 Other Other
```

If I understand `fct_lump()` correctly, I would have expected the columns fct2 and fct3 to be identical.

**Comment by zhiiiyang** [comment]
Come to join me if you would like to work on this issue together.

**Comment by zhiiiyang** [comment]
``` r
x <- data.frame(
  fct = factor(c("E", "T", "U", "K", "V", "Z")),
  wt = c(4, 2, 8, 4, 5, 4),
  stringsAsFactors = FALSE
)
print(x)
#>   fct wt
#> 1   E  4
#> 2   T  2
#> 3   U  8
#> 4   K  4
#> 5   V  5
#> 6   Z  4


dplyr::count(x, fct, wt=wt)
#> # A tibble: 6 x 2
#>   fct       n
#>   <fct> <dbl>
#> 1 E         4
#> 2 K         4
#> 3 T         2
#> 4 U         8
#> 5 V         5
#> 6 Z         4
```
**U and Z are the top two most common so other letters will be changed to 'Other'.**

```r
x$fct2 <- forcats::fct_lump(x$fct, w = x$wt, n = 2)
dplyr::count(x, fct2, wt=wt)
#> # A tibble: 3 x 2
#>   fct2      n
#>   <fct> <dbl>
#> 1 U         8
#> 2 V         5
#> 3 Other    14
```
**Now, U and Other are the top two most common so V will be changed to 'Other'.**

```r
x$fct3 <- forcats::fct_lump(x$fct2, w = x$wt, n = 2)
dplyr::count(x, fct3, wt=wt)
#> # A tibble: 2 x 2
#>   fct3      n
#>   <fct> <dbl>
#> 1 U         8
#> 2 Other    19
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
@zhiiiyang just to be clear, you're arguing that the current behaviour is correct, right?

**Comment by zhiiiyang** [comment]
> @zhiiiyang just to be clear, you're arguing that the current behaviour is correct, right?

Yes. I think the function works just fine if I didn't miss anything.

**Comment by zhiiiyang** [comment]
> Hmm I looked at the problem again and I am not so sure anymore if it is a bug. I think what I initially thought to be a bug arises somehow out of the logic of how ties are treated. Maybe it would be nice to have an option to strictly enforce a specific n?

This is what it does to several levels with ties: 

``` r
x <- data.frame(
  fct = factor(c("E", "T", "U", "K", "V", "Z")),
  wt = c(4, 2, 8, 4, 5, 4),
  stringsAsFactors = FALSE
)

x$fct2 <- forcats::fct_lump(x$fct, w = x$wt, n = 2)
x$fct3 <- forcats::fct_lump(x$fct, w = x$wt, n = 3)

print(x)
#>   fct wt  fct2  fct3
#> 1   E  4 Other     E
#> 2   T  2 Other Other
#> 3   U  8     U     U
#> 4   K  4 Other     K
#> 5   V  5     V     V
#> 6   Z  4 Other     Z
```
Besides the top two most common levels, i.e., U and V, they will also keep all the levels which are the third most common, i.e., E, K, and Z. So, it returns more than just n=3 levels if ties exsit. 

If it is not what you meant, could you give an example of what you would like to see? 

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by s-fleck** [comment]
If meant some option where, when I specify `n = 2`, I would get _exactly_ two levels, regardless of ties. This should probably be a separate issue/feature request though.

**Comment by s-fleck** [comment]
I think i did not understand correctly how ties are handled by `fct_lump()` when i filed this issue, and this is the explanation for the behaviour above.

**Comment by zhiiiyang** [comment]
Thank you for the clarification. Here is the quote of what `n` does in the function. 

> Positive n preserves the most common n values. Negative n preserves the least common -n values. It there are ties, you will get at least abs(n) values.

And I understand it now that people easily mistake `n` to be the total of levels returned and the explaination is kind of lost in all the texts. How about this? Let me add some more comments in the examples to point out that it returns the most common n values.
