### ISSUE TITLE
I am wondering if ignoring NAs should have a warning

### ISSUE THREAD

**Issue by orchid00** [tidyverse/forcats#119]
https://www.tidyverse.org/articles/2018/02/forcats-0-3-0/?utm_content=buffer44bb6&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

It says: In this latest release, NAs are properly ignored.
but, what if people don't know they have NAs?

this example 
```{r}
f <- factor(c("b", "b", NA, "a", "c", "c", "c", NA))
f
#> [1] b    b    <NA> a    c    c    c    <NA>
#> Levels: a b c
```

could we have a warning, that says your factor contains NA, even if NA is not a level?

**Comment by batpigandme** [comment]
This exists in `parse_factor()` which is the ~more conservative version of `factor()` vis-a-vis NAs.
Just quoting the [Getting Started](http://forcats.tidyverse.org/) here:
> The advantage of parse_factor() is that it will generate a warning if values of x are not valid levels:
``` r
library(tidyverse)
x1 <- c("Dec", "Apr", "Jan", "Mar")
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)
x2 <- c("Dec", "Apr", "Jam", "Mar")

factor(x2, month_levels)
#> [1] Dec  Apr  <NA> Mar 
#> Levels: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec

parse_factor(x2, month_levels)
#> Warning: 1 parsing failure.
#> row col           expected actual
#>   3  -- value in level set    Jam
#> [1] Dec  Apr  <NA> Mar 
#> attr(,"problems")
#> # A tibble: 1 x 4
#>     row   col expected           actual
#>   <int> <int> <chr>              <chr> 
#> 1     3    NA value in level set Jam   
#> Levels: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
```

Created on 2018-02-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by orchid00** [comment]
Yes, parse_factor exists.
However,  hypothetical question, let's say I updated my tidyverse packages, and I didn't check what details have been updated, and then I used factor() as before when NAs where not ignored and they were a level. Because now they are ignored, I might assume that I didn't have NA's? :/ I am just thinking in the possibility.

**Comment by batpigandme** [comment]
They were "ignored" in a way previously, that hasn't actually changed, it's that they couldn't then be used in, for example, `fct_inorder()`:
``` r
# forcats 0.2.0
library(forcats)
f <- factor(c("b", "b", NA, "a", "c", "c", "c", NA))
f
#> [1] b    b    <NA> a    c    c    c    <NA>
#> Levels: a b c
fct_inorder(f)
#> Error: `idx` must contain one integer for each level of `f`
```
You would know this previously because you were getting an error (see #89 ).

**Comment by orchid00** [comment]
Thank you!
