### ISSUE TITLE
Example of how to implement fct_explicit_na() on an entire dataframe

### ISSUE THREAD

**Issue by dalewsteele** [tidyverse/forcats#122]
I have a use case that involves adding an explicit <NA> factor level for all factors in a data.frame

See: [](https://stackoverflow.com/questions/49338118/how-to-replace-all-na-values-in-a-data-frame-use-forcatsfct-explicit-na/49370405#49370405)

I'm a tidyverse neophyte and ended up first getting a list of factors: 

`f_names <- names(Filter(is.factor, df))`
then using lapply to replace <NA> with a new factor level of "to_impute" via:

`df[, f_names] <- lapply(df[, f_names], function(x) fct_explicit_na(x, na_level = "to_impute")) %>% as.data.frame`

Occurs to me it might a useful example to illustrate the best way to do this in an example.

**Comment by batpigandme** [comment]
Might you be able to show this in a [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)?

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/). The [reprex dos and don'ts](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) are also useful.

**Comment by dalewsteele** [comment]
Sure.  See below:
``` r
library(tidyverse)
# Example dataframe with <NA>'s
df <- structure(list(loc_len = structure(c(NA, NA, NA, NA, NA, NA, 
                                           1L, 1L, 3L, 1L), .Label = c("No", "< 5 sec", "5 sec - < 1 min", 
                                                                       "1 - 5 min", "> 5 min", "Unknown duration"), class = "factor"), 
                     AMS = structure(c(1L, 2L, NA, 1L, 1L, NA, NA, NA, NA, NA), .Label = c("No", 
                                                                                           "Yes"), class = "factor")), .Names = c("loc_len", "AMS"), row.names = c(NA, 
                                                                                                                                                                   -10L), class = c("tbl_df", "tbl", "data.frame"))

# Get factor names
f_names <- names(Filter(is.factor, df))

# Convert each factor individually
df_new <- df  %>% 
  mutate(loc_len = fct_explicit_na(loc_len, na_level = "to_impute")) %>% 
  mutate(AMS = fct_explicit_na(AMS, na_level = "to_impute"))

# Tabulate results
lapply(df_new, function(x) data.frame(table(x, useNA = "always")))
#> $loc_len
#>                  x Freq
#> 1               No    3
#> 2          < 5 sec    0
#> 3  5 sec - < 1 min    1
#> 4        1 - 5 min    0
#> 5          > 5 min    0
#> 6 Unknown duration    0
#> 7        to_impute    6
#> 8             <NA>    0
#> 
#> $AMS
#>           x Freq
#> 1        No    3
#> 2       Yes    1
#> 3 to_impute    6
#> 4      <NA>    0

# Convert all factor variables at once
df[, f_names] <- lapply(df[, f_names], function(x) fct_explicit_na(x, na_level = "to_impute")) %>% as.data.frame

# Show via tables
lapply(df_new, function(x) data.frame(table(x, useNA = "always")))
#> $loc_len
#>                  x Freq
#> 1               No    3
#> 2          < 5 sec    0
#> 3  5 sec - < 1 min    1
#> 4        1 - 5 min    0
#> 5          > 5 min    0
#> 6 Unknown duration    0
#> 7        to_impute    6
#> 8             <NA>    0
#> 
#> $AMS
#>           x Freq
#> 1        No    3
#> 2       Yes    1
#> 3 to_impute    6
#> 4      <NA>    0
```

Created on 2018-03-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by huftis** [comment]
I think you simply want

```r
library(dplyr)
df = df %>% mutate_if(is.factor,
                      fct_explicit_na,
                      na_level = "to_impute")
```

I think this is the best (and ‘idiomatic’) way to apply `forcats` functions to several variables in a tibble. But it’s an example of using the `dplyr` package, which `forcats` doesn’t depend on, so I don’t think it can be added as an example in `forcats`.

**Comment by dalewsteele** [comment]
Very cool.  For newcomers to the tidyverse, such elegant and 'idiomatic' code snippets are invaluable!

**Comment by batpigandme** [comment]
@dalewsteele, I expect you're right re. dplyr, and functions like `mutate_if()` are there so you can operate over several columns, etc. 
Since it's a matter of a more generic operation, I'm going to go ahead and close the issue. That said, more forcats material with worked examples is in the works.
Thanks for the elegant solution, @huftis.
