### ISSUE TITLE
FR: `lvls_revalue` should accept expressions

### ISSUE THREAD

**Issue by ashiklom** [tidyverse/forcats#124]
For `ggplot`, I often want to make my labels use mathematical expressions, and the most straightforward way to do this is to modify the underlying factor levels.

```r
x <- factor(c("a", "b", "c"))
my_units <- c(expression(g ~ cm^{-2}), expression(m^2), expression(mu * g ~ cm^{-2}))
```

This works exactly as expected:
```r
levels(x) <- my_units
```

However, this currently fails with an error because `my_units` is not a character vector.
```r
x <- forcats::lvls_revalue(x, my_units)
```

I recognize why there is value in forcing levels to be character vectors...but perhaps there could be another function (`lvls_revalue2`?) that is not as strict, and is basically just a pipe-friendly alias for `levels<-`?

**Comment by hadley** [comment]
That just turns the expressions into strings, so creating them as expressions in the first place didn't really do anything:

``` r
x <- factor(c("a", "b", "c"))
my_units <- c(expression(g ~ cm^{-2}), expression(m^2), expression(mu * g ~ cm^{-2}))
levels(x) <- my_units
levels(x)
#> [1] "g ~ cm^{\n    -2\n}"      "m^2"                     
#> [3] "mu * g ~ cm^{\n    -2\n}"
```

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
