### ISSUE TITLE
allow `fct_inorder()` to tolerate `NA`s

### ISSUE THREAD

**Issue by corybrunson** [tidyverse/forcats#129]
`fct_inorder()` throws an error when a character vector, or even a factor, contains missing values. This occurs at the `length(idx) != nlevels(f)` stop criterion in `lvls_reorder()`.

This behavior might be justified by the uncertainty of the "true" order due to the missing values, but missingness also imposes uncertainty on the frequency of factor levels, and `fct_infreq()` is not sensitive to `NA`s in the same way.

Since factor variables often have missing values, it makes more sense to me not to require an additional step to put a factor with missing values in order. I'm sorry if this has been addressed elsewhere; i didn't find any mention in the previous issues.

Thanks for any feedback! If this sounds to others like a reasonable change, i can try a fix and submit a PR.

``` r
library(forcats)

fct_inorder(letters)
#>  [1] a b c d e f g h i j k l m n o p q r s t u v w x y z
#> Levels: a b c d e f g h i j k l m n o p q r s t u v w x y z
fct_inorder(c(letters, NA))
#> Error: `idx` must contain one integer for each level of `f`
fct_inorder(as.factor(c(letters, NA)))
#> Error: `idx` must contain one integer for each level of `f`

lvls_reorder(letters, 1:26)
#>  [1] a b c d e f g h i j k l m n o p q r s t u v w x y z
#> Levels: a b c d e f g h i j k l m n o p q r s t u v w x y z
lvls_reorder(letters, c(1:26, NA))
#> Error: `idx` must contain one integer for each level of `f`

fct_infreq(c(letters, NA))
#>  [1] a    b    c    d    e    f    g    h    i    j    k    l    m    n   
#> [15] o    p    q    r    s    t    u    v    w    x    y    z    <NA>
#> Levels: a b c d e f g h i j k l m n o p q r s t u v w x y z
```

**Comment by batpigandme** [comment]
For ref. if this ends up going forward, here is the commit for allowing NAs in `fct_infreq()`
https://github.com/tidyverse/forcats/pull/98/commits/a337d9d1666622b70765bcd7b30eddb11a261678

**Comment by corybrunson** [comment]
Oh, thank you, and pardon me! I didn't check the development code.

**Comment by batpigandme** [comment]
Oh, no problem — it's in the released version, just thought the analogous code for `infreq` would be handy!

**Comment by corybrunson** [comment]
Oh, the ref actually takes me to a commit that solves this issue for `fct_inorder()`! I re-installed the package from GitHub and it now works as i'd expected. So i'll just look forward to the next CRAN release.
