### ISSUE TITLE
Add a cut() method

### ISSUE THREAD

**Issue by richierocks** [tidyverse/forcats#132]
`base::cut()` is a great function, but it has a high learning curve and can require several arguments specifying in order to get what you want.

Converting numbers into factors is common beginner stumbling point, and this package seems like a good place to have a method for it. In fact, the issue was briefly discussed here before. https://github.com/tidyverse/forcats/issues/82

I quite like the [`fancycut::fancycut()`](https://www.rdocumentation.org/packages/fancycut/versions/0.1.1/topics/fancycut), `tag = value` syntax since it is fairly intuitive and makes it easy to control the resulting factor levels. (See link for examples.) That function needs an overhaul though, and the package appears not to be developed any more.

Happy to explore syntax/implementation details if you think that this is worth pursuing.

**Comment by nicholasjhorton** [comment]
Do the routines described in http://ggplot2.tidyverse.org/reference/cut_interval.html provide a consistent and simpler approach?  That's been my goto for this problem.

**Comment by hadley** [comment]
This doesn't feel like a good fit for forcats to me; but I can't really describe why.

**Comment by adamleerich** [comment]
Just for the record, I am actively maintaining `fancycut`, I just don't see any need to change what it is doing.  :)

**Comment by eamoncaddigan** [comment]
FWIW I landed here because I assumed forcats would implement a better version of `cut()`.
