### ISSUE TITLE
Reversed order of `forcats::fct_recode` and `dplyr::recode`

### ISSUE THREAD

**Issue by seaaan** [tidyverse/forcats#134]
The order of the new and old names for `fct_recode` and `recode` are reversed. That is to say, `fct_recode(data, new_name = "old_name")` but `recode(data, old_name = "new_name")`. Perhaps this has been done intentionally, in which case please disregard this issue. I am suggesting that they be made consistent because as it is I have to look them up every time. 

Runnable example code: 
```
example_vector <- letters[1:5]
forcats::fct_recode(example_vector, new_name = "a")
dplyr::recode(example_vector, a = "new_name")
```

**Comment by hadley** [comment]
Oh that's terrible :disappointed:

I think to fix this we should review all functions with a similar interface in the tidyverse, pick the option that's used most commonly and them move to deprecated all the functions with the wrong interface. We'll also need to write up a [tidyverse principle](http://github.com/tidyverse/principles) to make sure we have a record of this decision.

**Comment by huftis** [comment]
There’s also:
```r
dplyr::rename(d, new_name = "a")
```
(BTW, I don’t think it’s actually possible to discover that this the correct syntax from reading the help page for `dplyr::rename()` – except perhaps by figuring it out from one of the examples.)

For the old `plyr::rename()` function, it’s the opposite order, though I don’t think this matter much.

**Comment by jennybc** [comment]
One advantage of `newname = "old_name"` is you can remember it because it works more like regular assignment: `x = y` means "x gets y".

**Comment by huftis** [comment]
> One advantage of `newname = "old_name"` is you can remember it because it works more like regular assignment: `x = y` means "x gets y".

On the other hand, a ‘from → to’ conversion sounds very natural.

**Comment by huftis** [comment]
> > One advantage of `newname = "old_name"` is you can remember it because it works more like regular assignment: `x = y` means "x gets y".
> 
> On the other hand, a ‘from → to’ conversion sounds very natural.

BTW, `fct_collapse()` uses the `newlevel = c("oldlevel1", "oldlevel2", "oldlevel3")` syntax. So my vote goes for the `newname = "oldname"` syntax.

**Comment by ilarischeinin** [comment]
There is also the obvious case of:
```r
select(d, newname = oldname)
```

**Comment by jtr13** [comment]
Also, it's not always clear with these functions when you need quotation marks and when you don't. (Finally after looking up `?fct_recode` countless times, I think I finally have `fruit="apple"` burned into memory.)

**Comment by batpigandme** [comment]
Thanks @jtr13. Adding quotation marks around new variable names is something that we're trying to fix/be consistent about now, so _definitely_ feel free to submit a PR or issue if you see it happening.

**Comment by sowla** [comment]
I'm claiming this for useR 2019 tidy dev day, but would love to work with anyone else who's interested in this issue! :)

**Comment by hadley** [comment]
I am now sure that the tidyverse standard way should be `new_name = old_name` because that matches the syntax of `mutate()`. And when relabelling factors, it should be `new_level = "old_level"` because `old_level` is not an existing variable.

**Comment by romainfrancois** [comment]
I'll check if https://github.com/tidyverse/dplyr/issues/4473 can be done in Tidyverse developer day too, but this is is ✅ 🎉 @sowla

**Comment by sowla** [comment]
Please let me know if it is @romainfrancois :)
