### ISSUE TITLE
`fct_relabel` taking a named vector as its anonymous function

### ISSUE THREAD

**Issue by brianwdavis** [tidyverse/forcats#140]
I was working with data where I didn't want to type out each level by hand in a single block with `fct_recode`, so I assumed there had to be a way to pass a named vector to rename levels. That did not work, with the informative message 

> `Evaluation error: Each input to fct_recode must be a single named string. Problems at positions: 1.`

While it wasn't immediately obvious to me why I would guess to try `fct_relabel`, I did, and that works fine:

```r
library(dplyr)
x <- letters[1:16]
names(x) <- levels(gss_cat$relig)

gss_cat %>% mutate(relig = fct_recode(relig, x))    # does not work
gss_cat %>% mutate(relig = fct_relabel(relig, ~x))  # works
```
Which replaces "Protestant" with "o" and "Orthodox-christian" with "f" and so on. (I realize this toy example could have used `fct_anon`, but my real use case was the reverse operation).

Is this intended behavior? Is this supported behavior? I didn't see it documented, but I'd be glad to add an example to the docs if so.

**Comment by Ryo-N7** [comment]
I'll work on this for tidy-dev-day
