### ISSUE TITLE
 no applicable method for 'as_factor' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by xuhuizhang** [tidyverse/forcats#145]
I tried to categorize a numerical vector by using as_factor()

`as_factor(c(1, 2, 3))`

The error hapeend. 

> Error in UseMethod("as_factor") : no applicable method for 'as_factor' applied to an object of class "c('double', 'numeric')"

But it works when comes to as.factor()

`as.factor(c(1, 2, 3))`
`[1] 1 2 3`
`Levels: 1 2 3`

**Comment by cderv** [comment]
`as_factor` methods only exists currently for _factor_ and _character_. Factor vector are associated with character vector. In base R, if you provide numeric, it will be coerce to character before any other operation. I believe `forcats` is more strict and let the user to the coercion to prevent any issue. It is why you have to pass character vector only in this package right now.  However, you can use forcats on already created factor by the base R `factor` package if you want. However, there is a order issue. (see below) Again, _forcats_ is strict and keep level in vector ordering. 

``` r
library(forcats)
# use factor
factor(c(1, 2, 3))
#> [1] 1 2 3
#> Levels: 1 2 3
# but levels are re-ordered
factor(c(1, 3, 2))
#> [1] 1 3 2
#> Levels: 1 2 3
as.factor(c(1, 3, 2))
#> [1] 1 3 2
#> Levels: 1 2 3
as.factor(as.character(c(1, 3, 2)))
#> [1] 1 3 2
#> Levels: 1 2 3
# forcats prevent level re-ordering
as_factor(as.character(c(1, 2, 3)))
#> [1] 1 2 3
#> Levels: 1 2 3
as_factor(as.character(c(1, 3, 2)))
#> [1] 1 3 2
#> Levels: 1 3 2
fct_inorder(as.character(c(1, 3, 2)))
#> [1] 1 3 2
#> Levels: 1 3 2
```

<sup>Created on 2018-09-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).<\sup>

**Comment by xuhuizhang** [comment]
Aha, a order issue🧐🧐, finally. Many thanks, It was a great help.

**Comment by hadley** [comment]
Seems reasonable to add it here.

**Comment by kbodwin** [comment]
I'll give it a go!

**Comment by AI-MOO** [comment]
in order to solve the problem use : 

`magrittr::extract()`

instead of:

`tidyr::extract`
