### ISSUE TITLE
fct_count(..., prop_OR_relative_OR_normalize_OR_freq= T)

### ISSUE THREAD

**Issue by grayskripko** [tidyverse/forcats#146]
I wasn't able to find a good short approach to do
```
c("a", "a", "b") %>% table() %>% prop.table()
```
using ```forcats``` package. I think it's pretty handy to use a special argument for this purpose as in [sklearn value_counts](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.Series.value_counts.html)

**Comment by hadley** [comment]
Maybe `c("a" ,"a", "b") %>% fct_count(prop = TRUE)`?

**Comment by grayskripko** [comment]
should be OK and more R-thonic :) than ```normalize```

**Comment by khailper** [comment]
On it.
