### ISSUE TITLE
Feature Request: Allow fct_reorder to Work with Non-Numeric Results of .fun

### ISSUE THREAD

**Issue by billdenney** [tidyverse/forcats#147]
This is the same issue as #103 with a different request.

It seems as though `fct_reorder()` and `fct_reorder2()` should only require that the results of the function are sortable not that they are numeric.  Lexicographical order for the below is consistent and well-defined, but a simple numerical mapping can be more complex when the input isn't as simple as the below.

My feature request is:  Can `fct_reorder()` and `fct_reorder2()` please allow non-numeric values?  It seems like it could be as simple as running `xtfrm()` on the results of `.fun`.

Related to this, can the documentation be updated to indicate what the return value of `.fun()` must be?

``` r
library(forcats)
fct_reorder(.f=LETTERS[1:3], .x=LETTERS[4:6], .fun=min)
#> Error: `fun` must return a single number per group
```

Created on 2018-09-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Seems reasonable to me.

**Comment by akgold** [comment]
Going to work on this for tidyverse dev day!

**Comment by billdenney** [comment]
@akgold, I generated a PR for this several days ago (but it didn't link because I misunderstood how automatic linking between PR and issues worked-- titles don't link).  Linked now.

**Comment by akgold** [comment]
@billdenney Ah, cool! Nevermind :)
