### ISSUE TITLE
Keep the order after collapsing: fct_collapse

### ISSUE THREAD

**Issue by zx8754** [tidyverse/forcats#150]
Relevant SO post:

- [Collapse, order and drop factors efficiently in dplyr](https://stackoverflow.com/q/52869745/680068)

**Comment by batpigandme** [comment]
Could you please post your reprex here as well? It's easier to go through issues if the code is all in one place. Thanks.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
