### ISSUE TITLE
Inconsistent behavior for fct_lump() when n or prop is a character

### ISSUE THREAD

**Issue by robinsones** [tidyverse/forcats#169]
While `fct_lump()` keeps all the levels if you set `n` equal to a character, it sets them all to other when you set `prop` equal to a character.

Reprex: 

``` r
library(forcats)
x <- factor(letters[rpois(10, 5)])
# this keeps all the levels
fct_lump(x, n = "a")
#>  [1] c c b f e c b c n h
#> Levels: b c e f h n

# this makes everything "Other"
fct_lump(x, prop = "a")
#>  [1] Other Other Other Other Other Other Other Other Other Other
#> Levels: Other
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

My personal opinion is that these should both result in an error instead, but I think they should at least be consistent.

**Comment by hadley** [comment]
Agreed, definitely should be an errror.
