### ISSUE TITLE
Forcats site header doesn't include vignette

### ISSUE THREAD

**Issue by robinsones** [tidyverse/forcats#171]
The [article](https://forcats.tidyverse.org/articles/forcats.html) is there if you click on vignette("forcats") in the README , but it's in not in the header like I thought it should be. Is there anything I should do to make it appear there?

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/17410158/51508293-90b2ab00-1dc2-11e9-857a-1bc4e9bd2503.png">

**Comment by hadley** [comment]
Looks like it's because I configured `_pkgdown.yaml` slightly incorrectly. Let me fix that since it's not super well documented.
