### ISSUE TITLE
Turn levels into numbers

### ISSUE THREAD

**Issue by hadley** [tidyverse/forcats#18]
``` R
levels(gss_cat$rincome)
#> [1] "No answer"      "Don't know"     "Refused"        "$25000 or more" "$20000 - 24999" "$15000 - 19999"
#> [7] "$10000 - 14999" "$8000 to 9999"  "$7000 to 7999"  "$6000 to 6999"  "$5000 to 5999"  "$4000 to 4999" 
#> [13] "$3000 to 3999"  "$1000 to 2999"  "Lt $1000"       "Not applicable"
```

Would be useful to have some moderately easy way to turn into a numeric vector. It wouldn't be magic (i.e. it wouldn't compute mean of values) - it would work like `fct_revalue()`, but create numeric vector, and unmentioned levels would become NAs.

**Comment by hadley** [comment]
or 

```R

gss_cat %>% 
  mutate(partyid = fct_recode(partyid,
    "Republican, strong" =           -3,
    "Republican, weak" =             -2,
    "Independent, near republican" = -1,
    "Indepedent" =                    0,
    "Independent, near democrat" =    1,
    "Democrat, weak" =                2,
    "Democrat, strong" =              3
  )) %>% 
  count(partyid)
```

**Comment by hadley** [comment]
For this to work naturally the new/old order needs to be flipped :/

**Comment by hadley** [comment]
@lionel- any thoughts here?

**Comment by lionel-** [comment]
Hmm... Could forcats reuse the dplyr's tools for recoding? Then we have `` `-3` = "Republican, strong" `` which is a bit non-optimal from both the UI and implementation viewpoints but at least we have the natural order and it's consistent with dplyr's recode functions.

Can this be an alias to `recode_factor()`? A downside is that the recoding code should probably be extracted out of dplyr then, to avoid the heavy dep.

PS: just saw the emojis on the repo page, had a good laugh :)

**Comment by satuhelske** [comment]
This would be exactly what I need.
