### ISSUE TITLE
fct_cross() fails if its inputs are 3 or more factors

### ISSUE THREAD

**Issue by ghost** [tidyverse/forcats#182]
```r
library(forcats)
fruit <- factor(c("apple", "kiwi", "apple", "apple"))
colour <- factor(c("green", "green", "red", "green"))
eaten <- factor(c("yes", "no", "yes", "no"))

fct_cross(fruit, colour, eaten)
#> Error: Column name `<fct>` must not be duplicated.
#> Use .name_repair to specify repair.
```

This issue also happens if there is more than 1 character vector included as input.

It seems to me that the issue gets fixed if the following line: 
```.data <- lapply(tibble::tibble(.f, !!!flist), check_factor)```

is changed to this:
```.data <- lapply(rlang::list2(.f, !!!flist), check_factor)```

**Comment by ibwoo** [comment]
This issue helped me immensely - I hadn't cottoned on to the fact that they couldn't all be factors. An easy enough workaround for the moment, but this does deserve to be fixed!
