### ISSUE TITLE
Default factor levels when coercing from logical

### ISSUE THREAD

**Issue by alejandroschuler** [tidyverse/forcats#185]
Hi folks, I'm not sure if `forcats` is the right place to raise this issue, so apologies in advance if this should go elsewhere.

I find it curious that `factor(c(TRUE, TRUE))` produces a factor with a single level: `TRUE`. If we are to imagine that factors are categories where we know all of the levels a-priori, wouldn't it make sense if logicals converted to factors preserved that a-priori knowledge of the two levels `TRUE` and `FALSE` (with a consistent order) regardless of whether or not one of those two levels does not appear in the data? It's a trivial fix using `levels=c("TRUE", "FALSE")`, but I find it to be so philosophically obvious that this should always happen that it should warrant default behavior. Perhaps something along the lines of:

```r
fct.default = base::factor
fct.logical = function(lgl, ...) base::factor(lgl, levels=c("TRUE", "FALSE"))
fct = function(x, ...) UseMethod("fct")
```

This is a sometimes a minor frustration for me when using `tidymodels` packages (and `caret` before that) which require a factor outcome for classification problems. Every now and again I end up in a corner case where I get errors like:

```r
 Error: In metric: `yardstick::sens`
`truth` and `estimate` levels must be equivalent.
`truth`: TRUE, FALSE
`estimate`: TRUE
```

**Comment by hadley** [comment]
Makes sense, but what about `NA`? There are three possible values of a logical vector after all.

**Comment by alejandroschuler** [comment]
NA behavior is the same as with `base::factor`.
```r
> fct(c(TRUE, FALSE, NA))
[1] TRUE  FALSE <NA> 
Levels: TRUE FALSE
> base::factor(c(TRUE, FALSE, NA))
[1] TRUE  FALSE <NA> 
Levels: FALSE TRUE
```
As is the case with other factors, `NA`s are represented as `NA`s, not as an explicit level. I would say this is the desired default behavior because although `NA` is a possible value that the variable can take _in the data_, it is not a value the variable can take _epistemologically_. If that behavior is desired, `fct_explicit_na` does the job as usual.

**Comment by alejandroschuler** [comment]
Perhaps the best place to implement this in `forcats` would be as a method of `as_factor`:
```r
as_factor.logical = function(lgl, ...) base::factor(lgl, levels=c("TRUE", "FALSE"), ...)
```

**Comment by alejandroschuler** [comment]
However, I don't think the justification for sorting by order of appearance (locale variation) applies to logicals (or numerics). So maybe
```r
as_factor.logical = function(lgl, ...) base::factor(lgl, levels=c("FALSE", "TRUE"), ...)
as_factor.default = function(x, ...) as.factor(x, ...)
```
What I'm not sure about is whether first level of the logical factor should be `FALSE` to be consistent with the first level of something like `as_factor(c(1,0))` being `0` (implying `yardstick.event_first=FALSE` should be default). It may be better to have `TRUE` come first to explicitly break the connection between logicals and integers (implying `yardstick.event_first=FALSE` should be default, as it is).

**Comment by hadley** [comment]
I think the default levels would match the default ordering, so they'd be `c("FALSE", "TRUE")`
