### ISSUE TITLE
Feature Request: Reorder within groups functionality

### ISSUE THREAD

**Issue by dylanjm** [tidyverse/forcats#188]
I'm sure this has been brought up before but can't seem to find a PR or Issue discussing it. Currently, there is no way to create a ggplot in which factors are ordered within facets. David Robinson has a helper function that solves this issue and I think it would be a good addition to the forecats library. 
https://github.com/dgrtwo/drlib/blob/master/R/reorder_within.R

Here is a small reprex of what I mean. This could be valuable native feature to forecats.
``` r
library(tidyverse)
library(nycflights13)
library(drlib)

flights %>% 
  group_by(origin, carrier) %>% 
  summarise(mean_delay = mean(dep_delay, na.rm = T)) %>% 
  ggplot(aes(x = reorder_within(carrier, mean_delay, origin, max), y = mean_delay)) + 
  geom_point() + 
  facet_grid(. ~ origin) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = -.1))
```

![](https://i.imgur.com/QOEtbV0.png)

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
The problem is this requires data structure other than a factor, so I think it's outside the scope of forcats.
