### ISSUE TITLE
fct_collapse() - change "Other" name

### ISSUE THREAD

**Issue by jamiefo** [tidyverse/forcats#194]
Hi,

For the fct_collapse() function there is an option to set group_other = TRUE/FALSE.
May there please be an option added to rename the "Other" group to anything we want so that it will minic a case_when statement.  It's inefficient to use both fct_collapse() and then fct_other() to rename the "Other" bucket.  I would want to name the catch all bucket to something of my choice.  This is a bit of a pain point for me when using it.  I believe most would run to a case_when() statement if this option was not updated.

james

**Comment by gtm19** [comment]
I did consider incorporating this into my fix (#176) for #172, but couldn't decide whether this flexibility should be confined to `fct_other()`.

@hadley?

**Comment by hadley** [comment]
@gtm19 I think it would be best as a separate PR. Maybe we could change the default of `group_other` to `NULL`, and then when it's a string we'd use that as the name of the other group? (We'd also need to check for `TRUE` to make sure it's backward compatible)

**Comment by gtm19** [comment]
@hadley Either that, or we could add an `other_level` argument which defaults to `"Other"` (for consistency with `fct_other()`). 

I think I prefer the latter, and this would still be backwards compatible.

**Comment by hadley** [comment]
Two arguments seem excessive for this simple feature. Maybe we should just use `other_level` and deprecate `group_other`?
