### ISSUE TITLE
Remove deprecated `rlang::invoke()` from `fct_cross()`

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/forcats#204]
Currently `rlang::invoke()` is used a couple of times in `fct_cross()`:
https://github.com/tidyverse/forcats/blob/fb11604d2e67f9ef325b1bebded93244dedcfb15/R/fct_cross.R#L28-L33

From tests get warning:
```
test-fct_cross.R:6: warning: gives correct levels
`invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `eval(expr())`instead.
```

I'm not sure which of the two would be preferable.

**Comment by hadley** [comment]
Off the top of my head, I’d guess exec()
