### ISSUE TITLE
`fct_*` on a grouped tibble

### ISSUE THREAD

**Issue by adisarid** [tidyverse/forcats#206]
This issue is related to issue #186, which did not get much attention.
The following code produces the reasonable result when you understand what grouping is, but the error message is not informative enough.

```
tibble(name = c("a", "b", "c")) %>% 
  group_by(name) %>% 
  mutate(new_name = fct_inorder(name))
```

Creates a new character which is chr instead of a factor.
Also yields a warning which is not very informative:

```
# A tibble: 3 x 2
# Groups:   name [3]
  name  new_name
  <chr> <chr>   
1 a     a       
2 b     b       
3 c     c    
Warning messages:
1: In mutate_impl(.data, dots, caller_env()) :
  Unequal factor levels: coercing to character
2: In mutate_impl(.data, dots, caller_env()) :
  binding character and factor vector, coercing into character vector
3: In mutate_impl(.data, dots, caller_env()) :
  binding character and factor vector, coercing into character vector
4: In mutate_impl(.data, dots, caller_env()) :
  binding character and factor vector, coercing into character vector
```

I wonder if a better outcome would be to "break" the normal `group_by` behavior into something like:

```
tibble(name = c("a", "b", "c")) %>% 
  group_by(name) %>% 
  ungroup() %>% mutate(new_name = fct_inorder(name)) %>% group_by(name)
```

**Comment by hadley** [comment]
This is really a dplyr issue and not a forcats issue, and it's somewhat resolved in dev dplyr:

``` r
library(dplyr, warn.conflicts = FALSE)
library(forcats)

tibble(name = c("a", "b", "c")) %>% 
  group_by(name) %>% 
  mutate(new_name = fct_inorder(name))
#> # A tibble: 3 x 2
#> # Groups:   name [3]
#>   name  new_name
#>   <chr> <fct>   
#> 1 a     a       
#> 2 b     b       
#> 3 c     c
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't think it's possible to fully resolve this issue; you just have to understand that it's not going to work if you try and have different level orders in different groups.
