### ISSUE TITLE
group_by with .drop=TRUE & summarize on empty dataframe with fct_explicit_na produces non-empty dataframe

### ISSUE THREAD

**Issue by stelsemeyer** [tidyverse/forcats#222]
Using `dplyr::group_by(., .drop=TRUE)` and `dplyr::summarize` on an empty data frame with `forcats::fct_explicit_na` produces non-empty data frame:

``` r
data <- dplyr::tibble(a = numeric(),
                      b = forcats::fct_explicit_na(factor()))
data <- dplyr::group_by(data, b, .drop = TRUE)
#> Warning: Factor `b` contains implicit NA, consider using
#> `forcats::fct_explicit_na`
dplyr::summarise(data, n = dplyr::n())
#> # A tibble: 1 x 2
#>   b         n
#>   <fct> <int>
#> 1 <NA>      0
```

<sup>Created on 2019-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would expect the result dataframe to be empty, but I might be mistaken. 
Thanks for checking! ✌️

**Comment by hadley** [comment]
`forcats::fct_explicit_na(factor())` doesn't do anything, so I think this is a dplyr issue.

And it seems fine in the dev version, so we must've fixed it incidentally:

``` r
library(dplyr, warn.conflicts = FALSE)

data <- tibble(a = numeric(), b = factor())
data <- group_by(data, b, .drop = TRUE)
summarise(data, n = dplyr::n())
#> # A tibble: 0 x 2
#> # … with 2 variables: b <fct>, n <int>
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
