### ISSUE TITLE
Feature request: fct_inalpha

### ISSUE THREAD

**Issue by melissakey** [tidyverse/forcats#227]
I was applying a group of algorithms on a data set, and trying to control the order in which the algorithms were displayed.  I want them grouped according to their type, then alphabetical within that.  Being algorithms, they were a mixed bag of upper/lower case letters, which presented a problem: all the sorting is case sensitive, such that upper case letters are displayed before lower case letters.

While it doesn't totally address my challenge, would a `fct_inalpha` function (as part of the `_inorder`, `_infreq`, and `inseq` group) be possible?  Code as follows:

```r
fct_inalpha <- function(f, ordered = NA)
{
  f <- check_factor(f)
  lvls_reorder(f, order(tolower(levels(f))), ordered = ordered)
}
```

**Comment by hadley** [comment]
`fct_inalpha()` just feels a bit too specific too me — it feels like this should be a special case of some other too. You can do it with `fct_relevel(f, ~.x[order(tolower(.x))])`, but that took me a few minutes to figure out, so I'm not proposing as a real solution. Regardless, it doesn't feel like quite the right for forcats to me.
