### ISSUE TITLE
better warning in fct_relevel when first argument is of length 1

### ISSUE THREAD

**Issue by AmeliaMN** [tidyverse/forcats#248]
I know this is more user error than anything, but I was just cleaning up some data with categorical variables and made this mistake more than once in a session. Essentially, when I go to use `fct_relevel()` I forget to specify the name of the vector I want to work on as the first argument. Instead, I just jump into the order of levels I want. The function does throw an error, but it took me a bit to see what the problem was. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(forcats)
data(gss_cat)
gss_cat %>% 
  count(marital)
#> # A tibble: 6 x 2
#>   marital           n
#>   <fct>         <int>
#> 1 No answer        17
#> 2 Never married  5416
#> 3 Separated       743
#> 4 Divorced       3383
#> 5 Widowed        1807
#> 6 Married       10117
gss_cat <- gss_cat %>%
  mutate(marital = fct_relevel("Married", "Never married", "Separated"))
#> Warning: Unknown levels in `f`: Never married, Separated
gss_cat %>%
  count(marital)
#> # A tibble: 1 x 2
#>   marital     n
#>   <fct>   <int>
#> 1 Married 21483

<sup>Created on 2020-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
```

I think there could be a little more conditional logic in this function so if you provide unknown levels **and** the first argument was of length 1, the warning would be something like

```
Warning: Your first argument wasn't a vector, did you forget to include your variable?
```
Very rarely am I working with a character vector of length 1, and I'd guess most folks are the same!

**Comment by hadley** [comment]
My main concern with implementing a hint here is that it's a relatively special purpose function, and implementing a hint is a lot of work because you have carefully analyse the potential failure mode to make sure the hint isn't going to be misleading.

A more general solution would be to insist that the first argument be a factor, but that's squarely in opposition to forcats current flexible interface (and changing that would break a lot of existing code).

**Comment by AmeliaMN** [comment]
Yeah, I don't like the idea of breaking the flexible interface! But I still maintain this hint could be helpful. What could I do to analyze the potential failure mode to be more convincing? Look at usecases of `fct_relevel` on github?

**Comment by hadley** [comment]
To make your case more convincing, I think you have two options:

* Consider how the same principle might be applied to other functions

* Create some sort of diagram that shows the possible input space (considering types and lengths), and what you're proposing to carve out for the hint. 

(Both would be even better 😄)
