### ISSUE TITLE
fcl_collapse and its cousins provide only a proper subset of the features of Relevel from the Epi package.

### ISSUE THREAD

**Issue by bxc147** [tidyverse/forcats#249]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by bxc147** [comment]
It would be useful to have those features available too in dplyr, particularly the possibility to refer to levels by number and the table look-up facility.
I would be happy to see these functionalities in another package, because it is really not an Epi-specific issue.
b.r. Bendix Carstensen, maintainer of Epi

**Comment by hadley** [comment]
I'd suggest filing issues to discuss specific features that forcats lacks.

**Comment by bxc147** [comment]
Sorry I am not a native English/GitHub speaker, what does 'filing issues' men in this context?

**Comment by bxc147** [comment]
mean, sorry

**Comment by hadley** [comment]
To create this page you "filed an issue". So repeat but filling in with the details of what you actually want, rather than assuming we know what Epi provides but forcats does not.

**Comment by bxc147** [comment]
Thanks for the reply, I was merely pointing to a functionality you might be interested in.
R is open source so feel free to read further and snatch code from Epi.
If you have no interest in information that does not come in a particular format that is fine.
b.r. Bendix Carstensen

________________________________________
