### ISSUE TITLE
adding NA values to a factor

### ISSUE THREAD

**Issue by bczucz** [tidyverse/forcats#250]
As a part of the improved NA handling I would be very glad for a simpler & cleaner way for adding new NA values to a factor.
```
> x <- factor(1:3)
> fct_c(NA, x)
Error: All elements of `...` must be factors
```

The following works, but it looks less "tidy": 
```
> fct_c(factor(NA), x)
[1] <NA> 1    2    3   
Levels: 1 2 3
```

Thanks!
Balint

**Comment by hadley** [comment]
You can do that (and much more) with `vctrs::vec_c()`:

``` r
vctrs::vec_c(NA, factor(1:3))
#> [1] <NA> 1    2    3   
#> Levels: 1 2 3
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think at some point we'll eventually retire `fct_c()` in favour of this function.
