### ISSUE TITLE
Too many check_factor() in fct_rev()?

### ISSUE THREAD

**Issue by sindribaldur** [tidyverse/forcats#251]
Looking at what happens to an object passed to `fct_rev()`:

```r
lvls_reorder <- function(f, idx, ordered = NA) {
  f <- check_factor(f)
  # etc...


fct_rev <- function(f) {
  f <- check_factor(f)

  lvls_reorder(f, rev(lvls_seq(f)))
}
```

Wouldn't it be ok to omit the first `check_factor()` since check_factor() will deal with it later anyway within `lvls_reorder()`?

**Comment by hadley** [comment]
I don't think so, because `lvls_seq()` is also called on `f`.
