### ISSUE TITLE
Release-site build not updated to 0.4.0 (about to be 0.5.0)

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/forcats#256]
The `gh-pages` branch says that it's building the site for forcats 0.4.0.9000, but the release-version site still seems to reflect the pre-0.4.0 status (see [NEWS](https://forcats.tidyverse.org/news/index.html) with unreleased listed as 0.3.0.9000).

The [0.4.0 release](https://forcats.tidyverse.org/dev/news/index.html#forcats-040) is on the dev site, but doesn't seem to have gone to the release site.

I'm thinking this is probably a process problem.

**Comment by hadley** [comment]
Fixed with `usethis::use_github_action("pkgdown")`, which incorporates latest fixes.
