### ISSUE TITLE
Provide a warning message if `fct_*` is run on a grouping variable

### ISSUE THREAD

**Issue by adisarid** [tidyverse/forcats#267]
This is not a bug, but rather a suggestion on adding a warning message (which would have saved me many frustrations in a recent analysis).

When `fct_inorder` (perhaps all `fct_*`?) is run on a grouping variable, due to the grouping it might not rearrange the factor levels as intended.

```r
library(tidyverse)

example1 <- tibble(let = c("A", "C", "B"))

# works as expected:
example1 %>% 
  mutate(let = fct_inorder(let)) %>% 
  pull(let)
#> [1] A C B
#> Levels: A C B

# grouping messes things up:
example1 %>% 
  group_by(let) %>% 
  mutate(let= fct_inorder(let)) %>% 
  pull(let)
#> [1] A C B
#> Levels: A B C
```

Using the grouping made `fct_inorder` arrange the factors by lexicographic order.
Since I don't see many reasons someone would actually intend to use `fct_*` on a grouped variable, I suggest to add a soft warning message, in the spirit of:

`Using fct_* on a grouping variable may have unintended results. Consider using ungroup() before hand`.

**Comment by hadley** [comment]
Unfortunately I don't think we have any way to detect this currently.

**Comment by adisarid** [comment]
@hadley I see the problem, but I have an idea - perhaps we can check if the factor has a single level. Since there is no sense in running `fct_*` on a one level factor, it can be a reasonable indication for this type of error. See the if clause I added to `fct_inorder`:

```
fct_inorder_safe <- function (f, ordered = NA) 
{
  f <- forcats:::check_factor(f)
  if (length(unique(f)) == 1){
    warning("Singular level detected. Did you try fct_* on a grouped variable? try ungroup().")
  }
  idx <- as.integer(f)[!duplicated(f)]
  idx <- idx[!is.na(idx)]
  lvls_reorder(f, idx, ordered = ordered)
}
```

The only problem I see is that this warning message will appear for all groups, and we would prefer to show it only once. Maybe set it to run only once per session?

```
> example1 %>% 
+   group_by(let) %>%
+   mutate(let = fct_inorder_safe(let)) %>% 
+   pull(let)
[1] A C B
Levels: A B C
Warning messages:
1: Problem with `mutate()` input `let`.
i Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
i Input `let` is `fct_inorder_safe(let)`.
i The error occurred in group 1: let = "A". 
2: In fct_inorder_safe(let) :
  Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
3: Problem with `mutate()` input `let`.
i Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
i Input `let` is `fct_inorder_safe(let)`.
i The error occurred in group 2: let = "B". 
4: In fct_inorder_safe(let) :
  Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
5: Problem with `mutate()` input `let`.
i Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
i Input `let` is `fct_inorder_safe(let)`.
i The error occurred in group 3: let = "C". 
6: In fct_inorder_safe(let) :
  Singular level detected. Did you try fct_* on a grouped variable? try ungroup().
```

**Comment by hadley** [comment]
Hmmmmm, if we did that I think it would be more consistent in `check_factor()` but then I think it would probably have too many false positives.
