### ISSUE TITLE
Feature request: fct_stringsAsFactors() (Serious)

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/forcats#27]
I came to this package expecting to find a convenient method equivalent to:

```
library(dplyr)
dat %>%
mutate_if(is.character, as.factor)
```

The situation where you want to do this is just after you have finished preprocessing your data and it's time to funnel it into a bunch of ML methods and start scoring some models. Unfortunately models like `rf` are lazy and don't convert strings to factors automagically.

I would have made a pull but you don't import or suggest `dplyr` here.

**Comment by nicholas-vogt** [comment]
This seems pretty easy as it is - it's only two lines. Alternatively, could it be solved by using `as.data.frame(., stringsAsFactors = TRUE)`?

**Comment by jonocarroll** [comment]
I didn't think that *any* of the `fct_*` functions acted over a `data.frame` - they're all vector operations.

With that in mind, doesn't

```
fct_factor <- function(f) {
  if (is.character(f)) f <- as.factor(f)
  f
}
```
do the job (albeit trivially)?

**Comment by MilesMcBain** [comment]
I like your suggestion @nicholas-vogt. My only quibble is I would no longer have a tibble. But for the stated purpose of input to an algorithm, that is most likely fine.

@jonocarroll your function would need to be mapped to each column with `purrr::map_df()` or similar? I think that might be the slower way round. But a useful option all the same.

**Comment by MilesMcBain** [comment]
I reckon the case for this got a little stronger due to #39.

**Comment by huftis** [comment]
@MilesMcBain I think you want

```r
library(purrr)
df[] = map_if(df, is.character, factor)
```

**Comment by hadley** [comment]
For now, I don't think this belongs in forcats, as it's focused on individual vectors.
