### ISSUE TITLE
Re-licensing forcats

### ISSUE THREAD

**Issue by hadley** [tidyverse/forcats#275]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/tidyverse/forcats/graphs/contributors). @808sAndBR, @alberthkcheng, @alistaire47, @AmeliaMN, @billdenney, @gtm19, @jeremystan, @jhuovari, @jonocarroll, @jtr13, @kbodwin, @robinsones, @rtaph, @tslumley, @wilkox, @zhiiiyang, would you permit us to re-license forcats with the MIT license? If so, please comment "I agree" below.

* [x] [@808sAndBR](https://github.com/tidyverse/forcats/commits?author=808sAndBR)  
* [x] [@alberthkcheng](https://github.com/tidyverse/forcats/commits?author=alberthkcheng)  
* [x] [@alistaire47](https://github.com/tidyverse/forcats/commits?author=alistaire47)  
* [x] [@AmeliaMN](https://github.com/tidyverse/forcats/commits?author=AmeliaMN)  
* [x] [@billdenney](https://github.com/tidyverse/forcats/commits?author=billdenney)  
* [x] [@gtm19](https://github.com/tidyverse/forcats/commits?author=gtm19)  
* [x] [@jeremystan](https://github.com/tidyverse/forcats/commits?author=jeremystan)  
* [x] [@jhuovari](https://github.com/tidyverse/forcats/commits?author=jhuovari)  
* [x] [@jonocarroll](https://github.com/tidyverse/forcats/commits?author=jonocarroll)  
* [x] [@jtr13](https://github.com/tidyverse/forcats/commits?author=jtr13)  
* [x] [@kbodwin](https://github.com/tidyverse/forcats/commits?author=kbodwin)  
* [x] [@robinsones](https://github.com/tidyverse/forcats/commits?author=robinsones)  
* [x] [@rtaph](https://github.com/tidyverse/forcats/commits?author=rtaph)  
* [x] [@tslumley](https://github.com/tidyverse/forcats/commits?author=tslumley)  
* [x] [@wilkox](https://github.com/tidyverse/forcats/commits?author=wilkox)  
* [x] [@zhiiiyang](https://github.com/tidyverse/forcats/commits?author=zhiiiyang)

**Comment by billdenney** [comment]
I agree.

**Comment by robinsones** [comment]
I agree

**Comment by billdenney** [comment]
FYI, I am likely to be away from my computer for the next several weeks.  I have made contributions to other tidyverse packages, and I also agree for the other packages.  (Anticipating that I will see a similar message for the other packages coming up.)

**Comment by jhuovari** [comment]
I agree

**Comment by rtaph** [comment]
I agree

**Comment by jtr13** [comment]
I agree

**Comment by 808sAndBR** [comment]
I agree

**Comment by jeremystan** [comment]
I agree

**Comment by gtm19** [comment]
I agree

**Comment by gtm19** [comment]
I agree

**Comment by kbodwin** [comment]
I agree

**Comment by AmeliaMN** [comment]
I agree

**Comment by zhiiiyang** [comment]
I agree

**Comment by jonocarroll** [comment]
I agree

**Comment by alistaire47** [comment]
I agree

**Comment by alberthkcheng** [comment]
I agree

**Comment by wilkox** [comment]
I agree

**Comment by tslumley** [comment]
I agree
