### ISSUE TITLE
FR: purrr-style lambda functions in fct_reorder()

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/forcats#283]
When using fct_reorder(), I often have to use lambda functions on the go and find them very convenient.

Would it be possible to support purrr-style lambda functions in order to keep the compatibility with R<4.1?

``` r
library(tidyverse)
df <- tibble::tribble(
  ~color,     ~a, ~b,
  "blue",      1,  2,
  "green",     6,  2,
  "purple",    3,  3,
  "red",       2,  3,
  "yellow",    5,  1
)
df$color <- factor(df$color)
fct_reorder(df$color, df$a, \(x) min(x))
#> [1] blue   green  purple red    yellow
#> Levels: blue red purple yellow green
fct_reorder(df$color, df$a, ~min(.x))
#> Error in get(as.character(FUN), mode = "function", envir = envir): objet '.fun' de mode 'function' introuvable
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hadley** [comment]
Over the last year, it's become more clear that we want to shift away from purrr-style lambdas, so I'm no longer in favour of this change.

**Comment by DanChaltiel** [comment]
Could you explain why so? 
IMHO, purrr-style lambdas are incredibly clean and readable, much more than the new `\(x)` notation (which is also very annoying to type in non-querty keyboards).

**Comment by hadley** [comment]
Because it's available everywhere, not just in some functions.
