### ISSUE TITLE
Interaction of `fct_rev` and tibble groups

### ISSUE THREAD

**Issue by AlexJHomer** [tidyverse/forcats#288]
Might be that there's a reason for this that I'm completely overlooking, but...  Suppose we use `fct_rev` on a column of a tibble that is, initially, a vector of character strings.  If the tibble isn't grouped by that, it converts the column to factor and reverses the levels from the default (alphabetical/numerical) order.  But if the tibble is grouped by that variable, this doesn't happen, unless you first convert to factor, then reverse the order.  It's not sufficient to do this in one step of the mutate, either (`fct_level(factor(...))`); it's necessary to do it in two lines for it to work properly.

``` r
library(tidyverse)

num <- as.character(1:3)
dat <- tibble(num = num)

dat %>%
  mutate(num = fct_rev(num)) %>%
  pull(num) #The expected behaviour
#> [1] 1 2 3
#> Levels: 3 2 1

dat %>% group_by(num) %>%
  mutate(num = fct_rev(num)) %>%
  pull(num) #Doesn't reverse the levels now
#> [1] 1 2 3
#> Levels: 1 2 3

dat %>% group_by(num) %>%
  mutate(num = fct_rev(factor(num))) %>%
  pull(num) #Still does this; levels not reversed
#> [1] 1 2 3
#> Levels: 1 2 3

dat %>% group_by(num) %>%
  mutate(
    num = factor(num),
    num = fct_rev(num)
  ) %>% #Still grouped by `num`...
  pull(num) #but this works as expected
#> [1] 1 2 3
#> Levels: 3 2 1
```

<sup>Created on 2021-11-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
You can see what's happening here if you wrap the output in a list, so that dplyr doesn't automatically re-merge into a simple vector:

``` r
library(dplyr, warn.conflicts = FALSE)
library(forcats)

df <- tibble(num = c("1", "2", "3"))

df %>% 
  group_by(num) %>%
  mutate(num = list(fct_rev(num))) %>%
  pull(num) 
#> [[1]]
#> [1] 1
#> Levels: 1
#> 
#> [[2]]
#> [1] 2
#> Levels: 2
#> 
#> [[3]]
#> [1] 3
#> Levels: 3
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
