### ISSUE TITLE
Feature suggestion - extend fct_relevel( ) with after= argument

### ISSUE THREAD

**Issue by aleczwart** [tidyverse/forcats#29]
Hi Hadley, nice work on this package.

I'd like to suggest an extension to `fct_relevel()` - an `after=` argument (a single level specified as a character string or default `NA`) which specifies a level **after** which the other levels are to be placed, in the specified order.  This would be much more flexible than only moving levels only to the beginning of the level set.  

I have a `movebefore` function for re-ordering data frame columns which is surprisingly useful - often the desired ordering can be obtained with minimal typing with this function.  (I use 'before' rather than 'after', but 'after' might fit in better with the current behaviour of `fct_relevel()`...).

Cheers,
Alec

**Comment by hadley** [comment]
Seems reasonable to me - do you want to have a go at a PR?

**Comment by aleczwart** [comment]
Ø  Seems reasonable to me - do you want to have a go at a PR?
I’m new to all this, but, sure – why not?   I’ll take a look, see if I can implement a solution…

A
