### ISSUE TITLE
`fct_lump_prop()` errors with weights and unused levels

### ISSUE THREAD

**Issue by sam-crawley** [tidyverse/forcats#292]
When calling fct_lump_prop with weights, and with a factor that has unused levels, I get the error:

Error in if (prop > 0 && sum(prop_n <= prop) <= 1) { : 
  missing value where TRUE/FALSE needed

Reprex:

```r
f <- factor(c("a", "b", "c"), levels = c("a", "b", "c", "d"))
f <- fct_lump_prop(f, prop = 0.02,  w = c(1,1,1))
```

Calling fct_drop() beforehand prevents the error.

**Comment by hadley** [comment]
Reprex:

``` r
library(forcats)
f <- factor(c("a", "a", "b", "c"), levels = c("a", "b", "c", "d"))

fct_lump_prop(f, prop = 0.25)
#> [1] a     a     Other Other
#> Levels: a Other
fct_lump_prop(f, prop = 0.25, w = rep(1, 4))
#> Error in if (prop > 0 && sum(prop_n <= prop) <= 1) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
