### ISSUE TITLE
Inconsistent treatment of unicode characters in fct_recode()

### ISSUE THREAD

**Issue by sam-crawley** [tidyverse/forcats#313]
`fct_recode()` seems to modify unicode characters in some cases.

```r
z <- as_factor(c("d", "e", "f"))

z %>% fct_recode("\U0101" = "d")
```

Results in:

```
[1] a e f
Levels: a e f
```
(i.e. level "d" got changed to "a" instead of "ā").

Other unicode characters I've tried (e.g. "\U00B5") work correctly, and using `recode_factor()` also works.

**Comment by hadley** [comment]
This works for me:

``` r
library(forcats)

z <- as_factor(c("d", "e", "f"))
z |> fct_recode("\U0101" = "d") |> levels()
#> [1] "ā" "e" "f"
```

<sup>Created on 2022-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I suspect the problem is that you're on windows and have R 4.1 or earlier.

**Comment by sam-crawley** [comment]
Thanks, yes I was using R 4.1. Works fine in 4.2.
