### ISSUE TITLE
`fct()` doesn't work on factors

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/forcats#323]
Hi,

Like its old cousin `factor()`, it would be nice if `fct()` could be useful on factors too.
For instance, I would expect this to work with `fct()` (although I know I could do it with `fct_expand()`):

``` r
factor("a", levels=c("a", "b"))
#> [1] a
#> Levels: a b
factor("a", levels=c("a", "b")) %>% factor(levels=c("a", "b", "c"))
#> [1] a
#> Levels: a b c
```

In fact, when dealing with tables containing character and factor columns, it can happen to be very useful to be able to use `fct()` on both indifferently.

However, using `fct()` on factors will throw an error (unlike `factor()`):

``` r
a = factor("a")
factor(a)
#> [1] a
#> Levels: a
forcats::fct(a)
#> Error in `forcats::fct()`:
#> ! `x` must be a character vector
```

<sup>Created on 2022-12-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Even on factors, `fct()` would keep its loved advantages over `factor()`, such as preserving attributes.

**Comment by hadley** [comment]
I think this is probably a good idea, but I don't think it would preserve attributes; `fct()` is a constructor not a coercer.

**Comment by hadley** [comment]
I've changed my mind: I think `fct()` is basically a constructor function; and it should only work with character vectors.
