### ISSUE TITLE
Assigning a level to NULL in fct_collapse  does not remove it....

### ISSUE THREAD

**Issue by mosesotieno** [tidyverse/forcats#349]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
x <- factor(c("apple", "bear", "banana", "dear"))
fct_collapse(x, NULL = "apple", fruit = "banana")
```

**Comment by hadley** [comment]
I'm not sure why you expect that, but that's not what `fct_collapse()` does.
