### ISSUE TITLE
Could fct_reorder be easier to use for where `.desc = TRUE`?

### ISSUE THREAD

**Issue by davidhodge931** [tidyverse/forcats#362]
Maybe this is overkill, but wondering if it would be useful to have a specific function that relates to where .desc = TRUE in fct_reorder.

So either:

1. keep fct_reorder & add fct_reorder_desc function
2. deprecate fct_reorder, & add fct_reorder_asc and fct_reorder_desc functions

Could be something for tidy-dev-day?

**Comment by davidhodge931** [comment]
Or alternatively a function that specifies each in the name:
* `fct_reorder_ascend` 
* `fct_reorder_descend`

and deprecate `fct_reorder`

Maybe this is better, as it is more explicit - and there is only 2 options

**Comment by hadley** [comment]
That feels like a very specialised function, so at least for now I'd prefer to keep it as an argument.
