### ISSUE TITLE
Feature suggestion: fct_others that move all non given levels to other

### ISSUE THREAD

**Issue by lepennec** [tidyverse/forcats#40]
I often have to recode with a lot of not interesting levels that I want to replace by a single "Others" one. Because I'm lazy, I would like to give only the levels I want to keep...

I've made a prototype which does the job:

```R
fct_others <- function(f, ..., other_level = "Others") {
  f <- forcats:::check_factor(f)
  levels <- levels(f)
  new_levels <- if_else(levels %in% list(...), levels, other_level)
  f <- lvls_revalue(f, new_levels)

  # Place other at end
  levels <- levels(f)
  other_back <- c(setdiff(levels, other_level), intersect(levels, other_level))
  lvls_reorder(f, match(other_back, levels))
}
```

**Comment by hadley** [comment]
I took a slightly more verbose & general approach. I think the explicit `keep` and `drop` arguments will also make it slightly easier to guess at what `fct_other()` does when re-reading code.

**Comment by lepennec** [comment]
It's indeed much better! Thanks for your tremendous job!
