### ISSUE TITLE
Automatic variable name in return value of fct_count()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/forcats#44]
`fct_count()` is a welcome implementation of `dplyr::count()` for a factor that does not live in a data frame. I wonder if it could do a bit better at naming the variable that holds the factor levels?

``` r
library(forcats)
library(dplyr)

## the very best
count(iris, Species)
#> # A tibble: 3 × 2
#>      Species     n
#>       <fctr> <int>
#> 1     setosa    50
#> 2 versicolor    50
#> 3  virginica    50

## base can do it! with alot of help
as.data.frame(table(iris$Species, dnn = "Species"), responseName = "n")
#>      Species  n
#> 1     setosa 50
#> 2 versicolor 50
#> 3  virginica 50

## can fct_count do better?
fct_count(iris$Species)
#> # A tibble: 3 × 2
#>            f     n
#>       <fctr> <int>
#> 1     setosa    50
#> 2 versicolor    50
#> 3  virginica    50
```

**Comment by hadley** [comment]
My feeling is that this sort of magic belongs in another package - will think about it more in the context of tibble support for `summarise()`/`mutate()` since those functions will need to know how to generate good names.
