### ISSUE TITLE
Feature request: argument in fct_recode to reorder based on sequence

### ISSUE THREAD

**Issue by thercast** [tidyverse/forcats#45]
I struggled with making a clear title of this feature request, but here is my idea.  I really like using the `fct_recode` function to change the levels of factors (especially for plotting purposes) but I noticed that the new version of the factor keeps the same order of levels as the original version before the recoding using `fct_recode` even though I specified the order different in the arguments to `fct_recode`.  It would be nice to have an extra parameter in `fct_recode` to let the order be dictated by how the levels are given in the call.  Here's a minimal example using the forcats CRAN release of `0.1.1`:

```
library(forcats)
data(diamonds)

# show order of cut
levels(diamonds$cut)
# [1] "Fair"      "Good"      "Very Good" "Premium"   "Ideal"  

# recode levels using fct_recode
diamonds2 <- diamonds %>%
  mutate(cut2 = fct_recode(cut, "Very Great" = "Very Good", "Great" = "Good", "Really Ideal" = "Ideal", "Really Premium" = "Premium", "Bad" = "Fair"))

# show order of cut2
levels(diamonds2$cut2)
# [1] "Bad"            "Great"          "Very Great"     "Really Premium" "Really Ideal"  
```

**Comment by krlmlr** [comment]
Does `fct_rev()` and/or `fct_relevel()` work for you?

**Comment by epruesse** [comment]
Just ran into the same issue. I've got some data with nonsensically named classes and want to impose both new names and a sensible order at the same time. 

Since google led me here ... could you briefly explain a good way to do that? I.e. have a `fct_recode` that also relevels the factor in order of the arguments provided?

**Comment by epruesse** [comment]
In answer to myself:

```R
fct_reorg <- function(fac, ...) {
  fct_recode(fct_relevel(fac, ...), ...)
}
```

Works like this:

```
> x<-factor(c("a","b","c"))
> x
[1] a b c
Levels: a b c
> fct_recode(x, B="b", C="c")
[1] a B C
Levels: a B C
> fct_reorg(x, B="b", C="c")
[1] a B C
Levels: B C a
```

**Comment by sjackman** [comment]
I ran into this same question recently.
```r
relevel = c(
  "Alfa" = "A",
  "Bravo" = "B",
  "Charlie" = "C",
  "Delta" = "D")

after <- before %>%
  mutate(
    Var1 = fct_recode(fct_relevel(Var1, !!!relevel), !!!relevel),
    Var2 = fct_recode(fct_relevel(Var2, !!!relevel), !!!relevel))
```
