### ISSUE TITLE
Documentation for fct_reorder

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/forcats#53]
Seems something went awry in the doc for [fct_reorder](https://github.com/tidyverse/forcats/blob/87c9b134ea146f523457f12b830917166a7eff83/R/reorder.R#L8-L10) and the `x, y` arguments aren't documented very clearly 

```
#' @param x,y fun The levels of \code{f} will be reordered so that \code{fun}
#'    apply to each group is in ascending order.
#' @param fun An summary function. It should take one vector for
#'   \code{fct_reorder}, and two vectors for \code{fct_reorder2}.
```

(I think I get that they're the vectors used in `fun`). A quick grammar sweep wouldn't hurt. Looks like it's untouched since [first written](https://github.com/tidyverse/forcats/commit/9ee1bea45d03d77872a6e3dbb8f1bdf4d180dc61).

**Comment by hadley** [comment]
I have a hard time explaining this, but hopefully the new text is a little better.
