### ISSUE TITLE
fct_recode() with vectors of length > 1

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/forcats#56]
Is this behavior intended? It's not documented in the examples.

```r
fct_recode(letters, "vowel" = c("a", "e", "i", "o", "u"))
##  [1] vowel1 b      c      d      vowel2 f      g      h      vowel3 j      k      l     
## [13] m      n      vowel4 p      q      r      s      t      vowel5 v      w      x     
## [25] y      z     
## Levels: vowel1 b c d vowel2 f g h vowel3 j k l m n vowel4 p q r s t vowel5 v w x y z
```

If not, we should warn/throw, and perhaps direct the user to `fct_collapse()`.

**Comment by azankl** [comment]
This now throws an error, but the error message does not mention that `fct_collapse()` could probably due what the user wants. Should this be added?

**Comment by krlmlr** [comment]
Yeah, the help pages of `fct_recode()` and `fct_collapse()` could use some love. I'm not sure if the error message should mention this -- only if `fct_collapse()` is the only possible interpretation of the user's intention.

**Comment by krlmlr** [comment]
Would you like to contribute a PR?
