### ISSUE TITLE
Enhance semantics of prop in fct_lump()

### ISSUE THREAD

**Issue by vspinu** [tidyverse/forcats#65]
I think having a min number of occurrences rather than the minimal proportion is more useful.

So I would propose to generalize the meaning of `prop` argument. If `-1 < prop < 1` it means minimal proportion. If `prop >=1` get preserve values that appear at least prop times?

**Comment by vspinu** [comment]
> I'd rather add another argument or possible create another function.

`count` might be a reasonable name for the new argument. Thus, `n` is for most/least common `n` levels, `count` for levels with at least/at most `count`, and `prop` for least/most common fraction. 

Another function is an overkill IMO.

**Comment by ksedivyhaley** [comment]
I am also very interested in this feature.

In the meantime, I seem to have an ugly workaround. If I want to eg group items with over 2 occurrences:

```
#get the number of levels with more than 2 occurences

over_2 <-  sum( (count(  group_by(data, factor) ))$n>2 )

#plug this into fct_lump

data %>%
  mutate(factor = fct_lump(factor, n = over_2)
```

**Comment by hadley** [comment]
I'm pretty sure this is `fct_lump_min()`
