### ISSUE TITLE
Feature Suggestion - Function to Remove Specific Unused Levels

### ISSUE THREAD

**Issue by bschneidr** [tidyverse/forcats#69]
Sometimes you want to drop one or two specific unused factor levels but you don't want to drop _all_ of the unused factor levels. For example, you might have the following factor from survey data
```r
    vote_intention <- factor(x = c("Democrat", "Republican"), 
                             levels = c("Democrat", "Republican", 
                                        "Independent", "Undecided"))
```
where you'd be interested in removing the 'Undecided' level but not the 'Independent' level, even though both are unused. In such a case, you would essentially want to use a version of `fct_drop()` that doesn't drop _every_ unused level but instead allows finer control over which levels are dropped.

A simple example of such a function would be the following:
```r
fct_drop_specific <- function(f, l) {
          factor(x = f, 
                 levels = setdiff(levels(f), l),
                 ordered = is.ordered(f))
}

fct_drop_specific(f = vote_intention, l = "Undecided")
```
Forcats seems like the best package to have a function that would clearly accomplish this. Unless this is already implemented elsewhere, perhaps this could be implemented using arguments to `fct_drop()` or as a new function in forcats.

**Comment by hadley** [comment]
What should the function do if you request to drop a level that has values? Silently ignore and only drop levels that don't have any values? Or throw an error? Or silently replace all named levels with NA?
