### ISSUE TITLE
Add new factor type to allow adding levels on assignment

### ISSUE THREAD

**Issue by nalimilan** [tidyverse/forcats#74]
You asked on the blog announcement about things that `forcat` don't fix, so here's one. It would be useful to offer a factor type different from the standard one and which would accept new levels without a warning. As far as I know, this isn't handled by forcats currently. Silly example which is terribly annoying in practice:
```R
> df = data.frame(x=factor(c("1", "2")), y=factor(c("A", "B")))
> mutate(df, new=if_else(x == "1", x, y))
  x y  new
1 1 A    1
2 2 B <NA>
Warning message:
In `[<-.factor`(`*tmp*`, i, value = 2L) :
  invalid factor level, NA generated
```

(A special factor type would also allow protecting against the common mistake `as.integer(x)` vs. `as.integer(as.character(x))`, but that's a different issue.)

**Comment by hadley** [comment]
If you don't know the set of levels in advance, why are you using a factor and not a character vector?

**Comment by nalimilan** [comment]
Because I have an ordering of categories, and I'd just like the new levels to appear at the end. This happens often when creating a variant of a variable with a more detailed classification.

Also, in the specific case of `if_else`, copying the levels from the `true` operand is kind of an arbitrary choice.

**Comment by hadley** [comment]
I think that's a reasonable thing to want, but for now, it's outside the scope of forcats.
