### ISSUE TITLE
Error : object `as_factor' is not exported by 'namespace:forcats'

### ISSUE THREAD

**Issue by whatevergeek** [tidyverse/forcats#78]
Installation of TidyVerse is ok.
However, when loading the library: library(tidyverse). 
It throws the following issue:

Error : object `as_factor' is not exported by 'namespace:forcats'

Error: package or namespace load failed for `tidyverse'

**Comment by whatevergeek** [comment]
strange.. awhile ago i was getting this issue.. now, after posting... it's gone... strange...
anyone, i'm closing it now since it's not occuring anymore...

**Comment by ratnip** [comment]
I am having this issue now and it's driving me nuts. Can you remember if you did anything specific to solve it?

**Comment by whatevergeek** [comment]
not that i remember... 
the only specific thing i did was posting...
is it working for you now?

**Comment by tomascamargo** [comment]
I do have the same problem.

**Comment by leerssej** [comment]
I just ran into the same issue. Only thing new was getting my Rscript.exe to install.packages tidyverse all over again because I couldn't get it to work off of the packages loaded in R previously.

**Comment by leerssej** [comment]
I did this and tidyverse loaded up again.
```> remove.packages("tidyverse")
Removing package from ‘C:/Users/Koyot/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
> install.packages("forcats")
> install.packages("tidyverse")
```
good old tidyverse library loads as before.

**Comment by ratnip** [comment]
Thanks! That did the trick. :)

**Comment by tomascamargo** [comment]
Great. It now works.

**Comment by pnvolkmar** [comment]
I saw the same error as in the OP when I was installing tidyverse on my linux (16.10 Xubuntu) box. Installing forcats first as suggested fixed it! Thanks!

**Comment by Triamus** [comment]
Thanks @leerssej this worked for me! I had same issue on a Windows machine.

**Comment by NjoyStat** [comment]
Hi, I've installed R version 3.4.4 (2018-03-15) on a Windows machine and succesfully installed Rcmdr
but when I run
 
`>library(Rcmdr)`

I have a similar issue:

`Error: package or namespace load failed for ‘effects’:
 object ‘warnErrList’ is not exported by 'namespace:utils'
Errore: package ‘effects’ could not be loaded`

If I try to install "utils" I receive the following:

`Warning messages:
1: package ‘utils’ is not available (for R version 3.4.4) 
2: package ‘utils’ is a base package, and should not be updated`

I've tried everything else from your previous posts and still doesn't work...

any suggestion?

**Comment by kevinrue** [comment]
@NjoyStat this is not exactly the same error, and as such should be open in a separate issue.
With that said I ran into the same problem as you on a macOS high Sierra with R 3.5.0 when i tried to `install.packages("lme4")`.
Can't figure it out yet

**Comment by NjoyStat** [comment]
@kevinrue in my case the problem was solved by 

`> install.packages('nlme')`

before installing Rcmdr

**Comment by kevinrue** [comment]
Thanks. I'm just in the process of updating a whole lot of packages, but I'll try as soon as this completes.
