### ISSUE TITLE
forcats as_factor has no applicable method for "labelled"

### ISSUE THREAD

**Issue by arhot** [tidyverse/forcats#79]
The forcats function as_factor has no method for class "labelled" (or dataframe), while the as_factor in haven does. I don't know if there's a reason to have the less generic function in forcats, but if so, clearer naming should be considered.

**Comment by hadley** [comment]
I don't understand what the problem is

**Comment by arhot** [comment]
Hmm, I'm not sure if you mean you don't know what I mean or you don't see how it's a problem, but I'll try to explain:

forcats::as_factor() and haven::as_factor() are different, subtly: the latter has more methods. For the user, the order you load your packages matters etc.

I think that is a problem, as I feel tidyverse packages should not have functions with the same name that do different things if it can be avoided. backwards compatibility etc sometimes mean it can't, but I don't think any of those apply here.

Of course, you may disagree and find naming different functions the same appropriate - after all, users can always just make sure they use the correct package version. 

I'd suggest replacing the function in forcats with the haven version, as I don't see any harm in doing it.

**Comment by hadley** [comment]
But they're the same function? haven now imports `forcats::as_factor()`

**Comment by arhot** [comment]
I must be confused somewhere - I currently have the CRAN versions, forcats_0.2.0 and haven_1.0.0 ,attached, and 

s1 <- labelled(c("M", "M", "F"), c(Male = "M", Female = "F"))
haven::as_factor(s1)
forcats::as_factor(s1) 

The first gives 
[1] Male   Male   Female
Levels: Female Male

The second
Error in UseMethod("as_factor") : 
  no applicable method for 'as_factor' applied to an object of class "labelled"

When only forcats is attached, methods(as_factor) gives [1] as_factor.character* as_factor.factor*.
When only haven is attached, methods(as_factor) gives [1] as_factor.character*  as_factor.data.frame* as_factor.factor*     as_factor.labelled* .

This matches the package reference manuals on CRAN (https://cran.r-project.org/web/packages/haven/haven.pdf and https://cran.r-project.org/web/packages/forcats/forcats.pdf).

I probably have an issue with package versions or something similar, but I can't figure out what.

**Comment by hadley** [comment]
Oh sorry it's fixed the dev versions. That's where the confusion is 🙂

**Comment by arhot** [comment]
The issue still persists in the dev version 0.2.0.9000.

**Comment by jakobarendt** [comment]
Another question and sorry, in advance, if that is not the adequate thread.
But why are the help files different for `forcats::as_factor` and `haven::as_factor` if haven just imports `forcats::as_factor`?

Thanks for the help in advance!

![image](https://user-images.githubusercontent.com/78620868/174116696-748c0cbe-8c7b-43b4-9e9a-04a3fffd5bc9.png)
![image](https://user-images.githubusercontent.com/78620868/174116890-2bfccc18-0f06-4367-992a-f6bf82c78854.png)
