### ISSUE TITLE
function to apply function to the levels of a factor

### ISSUE THREAD

**Issue by felipegerard** [tidyverse/forcats#80]
I've been working with factors that have very long names. When I want to plot them things get confusing. I wrote a function that puts linebreaks every e.g. 5 words (let's call it `split_long`). I didn't find an elegant way of applying said function to the levels of a factor in one step (so as to avoid intermediate steps).

I wrote a function `fct_map_levels(fctr, fun)`, which returns `fctr` after having applied `fun()` to each of its levels (using `purrr::map_chr()` for robustness). It's simple but saves a lot of time! Now I can simply do:

    qplot(fct_map_levels(fctr_with_long_names, split_long), data=my_df)

I think this would help round `forcats` but I don't know where to put it in the existing code. Should I add it? If so, where?

**Comment by hadley** [comment]
Isn't this `fct_relabel()`?

**Comment by felipegerard** [comment]
Yes, thank you. I think it didn't exist back when I opened this issue.
