### ISSUE TITLE
Feature request: pass one longe recode vector to fct_recode

### ISSUE THREAD

**Issue by s-fleck** [tidyverse/forcats#81]
It would be nice if you could just pass one long vector to fct_recode and similar functions, like:
```
x <- c('2', '3')
rec <- c('two' = '2', 'three' = '3')
forcats::fct_recode(x, rec)
```
Actually this is more of a regression-request than a feature request, since the code above worked in older versions of forcats, before you improved the argument check for `fct_recode`. Maybe you could
add something like the .dots argument for the dplyr standard evaluation functions?

**Comment by CG1122** [comment]
+1

Had literally just come on here to request this as well.  In general with mappings I like to define all static maps  in advance using named vectors or lists. It would be incredibly useful to have fct_recode accept these as an input.

**Comment by hadley** [comment]
Now part of #110 - you'll be able to do `forcats::fct_recode(x, !!!rec)` once that's implemented.
