### ISSUE TITLE
Collapsing numbers into factors

### ISSUE THREAD

**Issue by pbiecek** [tidyverse/forcats#82]
Are you considering new functions in the forcats  package, like:
num_cut - numeric to ordered factor with k levels, equal lengths of intervals
num_cut2 - numeric to ordered factor with k levels, equal sizes

**Comment by pbiecek** [comment]
This package looks like a better place for these functions than ggplot2

**Comment by lorenzwalthert** [comment]
Our package [`refactor`](https://github.com/jonmcalder/refactor) (which is WIP) might provide the  functionality you are looking for -namely as a S3 generic for `cut`. Works for both integers and ordered factors and features similar arguments as the default method `cut`.

**Comment by pbiecek** [comment]
@lorenzwalthert thanks for info,
I will look into your package
