### ISSUE TITLE
fct_recode(), rename factor level to f doesn't work

### ISSUE THREAD

**Issue by Tazinho** [tidyverse/forcats#84]
The following gives an error, since f is also the name of the data argument.
Is there a recommended workaround for these situations?

> a <- factor(letters[1:5])
> forcats::fct_recode(a, f= "a", h = "b")
Error: Each input to fct_recode must be a single named string. Problems at positions: 1

**Comment by QuentinRoy** [comment]
Same issue. I believe the problem is that 'f' is recognized as false here:
```r
  is_ok <- function(x) is.character(x) && length(x) == 1
  ok <- vapply(levels, is_ok, logical(1))
```

**Comment by hadley** [comment]
Thanks for the bug report! I'll attack this systematically as part of #110

**Comment by gabrielburcea** [comment]
i got this problem for fct_recode. I have useed !!! and haven't succeded .. 

Each input to fct_recode must be a single named string. Problems at positions: 1, 2

**Comment by batpigandme** [comment]
Commenting on a closed issue is pretty low visibility. Before opening a new thread here, let's see if we can get things sorted on https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)
