### ISSUE TITLE
FR: When calling fct_reorder, having the ability to anchor some levels at the top or bottom of the order

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/forcats#85]
After using `fct_other` , it's pretty common that we would wish to have the newly created Other level at the bottom of a chart, since it's an amalgamation of rarely occurring levels. It would be useful if when we call `fct_reorder`, we can list a vector of levels that we want at the top or the bottom of a list of levels, such as the aforementioned "Other" level.

Please let me know if I should create a separate issue, but another useful feature for `fct_lump` is to have the ability to always exclude or always include specific levels. We could run a situation where we always want a specific level to show on a plot, regardless of its frequency.

**Comment by gregrs-uk** [comment]
Could you use `fct_relevel`? For example:

```
> (f <- factor(c('Antelope','Other','Zebra')))
[1] Antelope Other    Zebra   
Levels: Antelope Other Zebra
> fct_relevel(f, 'Other', after=Inf)
[1] Antelope Other    Zebra   
Levels: Antelope Zebra Other
```

**Comment by philstraforelli** [comment]
@gregrs-uk Using `fct_relevel()` in cases where there are many levels would be tedious.

**Comment by gregrs-uk** [comment]
From your original question, it seems like you want to take a factor output from `fct_other`, reorder the levels based on another variable using `fct_reorder` then move the 'Other' level to be the first or last level. You can use `fct_relevel` to do this.

``` r
library(forcats)
library(tibble)
library(dplyr)
library(ggplot2)

data <- tibble(Animal = c('Antelope','Badger','Cat','Zebra'),
               Count = c(5, 2, 2, 3))

# lump badgers and cats together into 'Other'
summary <- data %>%
  mutate(Animal = fct_other(Animal, keep = c('Antelope', 'Zebra'))) %>%
  group_by(Animal) %>%
  summarise(Count = sum(Count))

summary
#> # A tibble: 3 x 2
#>   Animal   Count
#>   <fctr>   <dbl>
#> 1 Antelope  5.00
#> 2 Zebra     3.00
#> 3 Other     4.00

summary %>%
  mutate(Animal = fct_reorder(Animal, Count), # order animals by count
         Animal = fct_relevel(Animal, 'Other', after = Inf)) %>% # move other level
  ggplot(aes(Animal, Count)) +
  geom_col()
```

![](https://i.imgur.com/sI3fb9s.png)

You could also modify `after = Inf` to `after = 0` if you want 'Other' at the other end of the chart.

If this isn't what you want to do, perhaps you could supply a minimum working example to demonstrate your issue.

**Comment by hadley** [comment]
@gregrs-uk's solution seems reasonable to me. Generally, we want each individual function to be kept simple, and you solve more complex problem by stringing together simple pieces.
