### ISSUE TITLE
Add warning or error for unused arg in `as_factor()`

### ISSUE THREAD

**Issue by davechilders** [tidyverse/forcats#87]
`as_factor(c("hello", "hadley"))` works as expected. 

A common error is to not wrap the vector in `c()`:

In this case, `base::as.factor()` throws a reasonable error:

```
> as.factor("hello", "hadley")
Error in as.factor("hello", "hadley") : unused argument ("hadley")
```

But `as_factor()` silently drops the extra argument:

```
> as_factor("hello", "hadley")
[1] hello
Levels: hello
```

Perhaps an error or warning would be appropriate?

**Comment by hadley** [comment]
@jimhester in general, do you think it's a good idea to throw an error in methods when `...` is occupied but now used?

**Comment by jimhester** [comment]
Ideally yes, but I could see this being an issue when methods call `NextMethod()`, e.g.

``` r
print.foo <- function(x, ..., abc = 123) {
  print(abc)
  NextMethod("print")
}

print.bar <- function(x, ...) {
  if (rlang::dots_n(...)) {
    rlang::abort("Invalid argument")
  }
  cat(x)
}

foobar <- structure(1, class = c("foo", "bar"))
print(foobar)
#> [1] 123
#> 1
print(foobar, abc = "hi")
#> [1] "hi"
#> Error: Invalid argument
```

Created on 2018-02-13 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by hadley** [comment]
Oh yeah, I knew it wasn't a good idea, but I forgot the reason.

**Comment by hadley** [comment]
@davechilders sorry, this is the downside of making a generic version of `as.factor()` and hence needing `...` so method can have their own arguments.
