### ISSUE TITLE
Issue loading library(rcompanion)

### ISSUE THREAD

**Issue by GlynisHumphrey** [tidyverse/forcats#90]
Could anyone advise how to solve the below issue? I've tried uninstalling and the same issue reappears. Any advice would be appreciated. 

Error : object ‘ordiYbar’ is not exported by 'namespace:vegan'

In addition: Warning message:
package ‘rcompanion’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘rcompanion’

**Comment by medong** [comment]
I had the same issue. Then I updated the vegan package and the problem solved.
