### ISSUE TITLE
fct_explicit_na() throws error when column is all NAs

### ISSUE THREAD

**Issue by NBRAYKO** [tidyverse/forcats#93]
Not sure if this was intended, but when using `fct_explicit_na` to code NAs does not work if your column is all NAs
```
c(NA, "Has level") %>% fct_explicit_na(na_level = "Miss")
[1] Miss Has level  

> c(NA, NA) %>% fct_explicit_na(na_level = "Miss")
Error: `f` must be a factor (or character vector).
```

This works, but not as intuitive or convenient 
```
> c(NA, NA) %>% factor() %>% fct_explicit_na(na_level = "Miss")
[1] Miss Miss
Levels: Miss
```

**Comment by hadley** [comment]
I think this is correct - forcats methods only work on character and factor columns, and you have a logical column. I think you're better off fixing this upstream (i.e. why isn't it factor column currently?).
