### ISSUE TITLE
Return an ordered factor with as_factor

### ISSUE THREAD

**Issue by dannyparsons** [tidyverse/forcats#94]
It would be nice if `as_factor` could optionally return an ordered factor.

I think this is straightforward for characters: Since `fct_inorder` has an `ordered` parameter and this is called by `as_factor.character` could an ordered parameter be passed through instead of what it is doing now and just calling `fct_inorder(x)`?

A question might then be whether you should also modify `as_factor.factor` to be able to accept the same for consistency.

**Comment by bhive01** [comment]
Just ran into this just now. Wanted to order names of the week and couldn't pass the levels as ordered using as_factor()

```r
library(tidyverse)
fruit <- structure(list(DOW = c("Friday", "Monday", "Thursday", "Tuesday", 
"Wednesday"), FruitPerDayofWeek = c(17620L, 9977L, 7511L, 15456L, 
15598L)), class = c("tbl_df", "tbl", "data.frame"), .Names = c("DOW", 
"FruitPerDayofWeek"), row.names = c(NA, -5L))

# sort alphabetical, expected
fruit %>%
  arrange(DOW)

#sort by factor level, doesn't
fruit %>%
  mutate(DOW = as_factor(DOW, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
  arrange(DOW)
```

@karawoo pointed out I could use ordered() instead. 
```r
library(tidyverse)
fruit <- structure(list(DOW = c("Friday", "Monday", "Thursday", "Tuesday", 
"Wednesday"), FruitPerDayofWeek = c(17620L, 9977L, 7511L, 15456L, 
15598L)), class = c("tbl_df", "tbl", "data.frame"), .Names = c("DOW", 
"FruitPerDayofWeek"), row.names = c(NA, -5L))

# sort alphabetical, expected
fruit %>%
  arrange(DOW)

#sort by factor level, does with ordered
fruit %>%
  mutate(DOW = ordered(DOW, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
  arrange(DOW)
```
CC @jennybc

**Comment by hadley** [comment]
I don't like the idea of a coercion function returning a different class depending on an argument. And diven that there are existing work-arounds, I don't think it's needed.

**Comment by bhive01** [comment]
I see your point. Perhaps this is a documentation problem then? I don’t
remember this being clear in the docs or perhaps it could be handled via a
warning when “levels” are passed to this function?
