### ISSUE TITLE
Consistency in taking character input

### ISSUE THREAD

**Issue by michaellevy** [tidyverse/forcats#99]
Some functions seem to take a character input fine, which I assumed was by design. `fct_expand` at least doesn't, and returns this rather unintuitive error: `Error in mutate_impl(.data, dots) : Evaluation error: is.list(x) is not TRUE.`

**Comment by hadley** [comment]
Fixed - in the future, feel free to submit a PR yourself if you spot a function that is missing `check_factor()`.
